export const CLASS1 = {
  asp11: ["aspect-1-1"],
  vh100: ["vh-100"],
  bgLight: ["bg-white"],
  bgLight2: ["bg-light"],
  bgDark: ["bg-dark"],
  row: ["row"],
  col6: ["col-6"],
  pFixed: ["position-fixed"],
  pRel: ["position-relative"],
  pAbs: ["position-absolute"],
  pSticky: ["position-sticky"],
  dFlexiCenter: ["d-flex", "align-items-center"],
  aiCenter: ["align-items-center"],
  rowReverse: ["flex-row-reverse"],
  pSE: ["start-0", "end-0"],
  pS: ["start-0"],
  pB: ["bottom-0"],
  pE: ["end-0"],
  pT: ["top-0"],
  pd2: ["p-2"],
  pdy1: ["py-1"],
  pdx2: ["px-2"],
  pdy2: ["py-2"],
  pdy3: ["py-3"],
  pdx3: ["px-3"],
  pdx7: ["px-7"],
  pdy7: ["py-7"],
  pdt2: ["pt-2"],
  pdb2: ["pb-2"],
  pdb5: ["pb-5"],
  br5: ["br-5"],
  m0: ["m-0"],
  mxauto: ["mx-auto"],
  my2: ["my-2"],
  mx2: ["mx-2"],
  mx3: ["mx-3"],
  my3: ["my-3"],
  mx1: ["mx-1"],
  me1: ["me-1"],
  me2: ["me-2"],
  me3: ["me-3"],
  mt2: ["mt-2"],
  mb2: ["mb-2"],
  fFill: ["flex-fill"],
  dFlex: ["d-flex"],
  dNone: ["d-none"],
  fColumn: ["flex-column"],
  jCenter: ["justify-content-center"],
  jStart: ["justify-content-start"],
  jEnd: ["justify-content-end"],
  jBetween: ["justify-content-between"],
  tlf12: ["text-light", "fs-12"],
  tdf12: ["text-dark", "fs-12"],
  f12: ["fs-12"],
  fwLight: ["fw-light"],
  fwBold: ["fw-bold"],
  tCenter: ["text-center"],
  tStart: ["text-start"],
  ttrun: ["text-truncate"],
  btn: ["btn", "btn-sm"],
  btnPri: ["btn-primary"],
  btnLight: ["btn-light"],
  shadow: ["shadow-sm"],
  border: ["border"],
  flowY: ["overflow-y"],
  flow0: ["overflow-0"],
  borderNone: ["border", "border-0"],
  borderY: [
    "border",
    "border-2",
    "border-start-0",
    "border-end-0",
  ],
  borderRight: [
    "border",
    "border-2",
    "border-end-0",
    "border-bottom-0",
    "border-top-0",
  ],
  borderleft: [
    "border",
    "border-2",
    "border-start-0",
    "border-bottom-0",
    "border-top-0",
  ],
  borderBot: [
    "border",
    "border-2",
    "border-start-0",
    "border-end-0",
    "border-top-0",
  ],
  border2: ["border", "border-2"],
  rounded: ["rounded"],
  rounded0: ["rounded-0"],
  dropBox: ["bg-dark", "border", "rounded", "w-200", "py-2"],
  btnBorderLight: [
    "btn",
    "btn-sm",
    "btn-light",
    "bg-white",
    "text-dark",
    "fs-12",
    "d-flex",
    "align-items-center",
    "justify-content-between",
  ],
};

export const CLASS2 = {
  layerTop: {
    zIndex: 9999,
  },
  layerMid: {
    zIndex: 999,
  },
  h100: {
    height: "100px",
  },
  h100p: {
    height: "100%",
  },
  w100p: {
    width: "100%",
  },
  w100: {
    width: "100px",
  },
  h150: {
    height: "150px",
  },
  h300: {
    height: "300px",
  },
  w300: {
    width: "270px",
    height: "max-content",
  },
  w90: {
    width: "90px",
  },
  headerFile: {
    minWidth: "200px",
  },
  controller: {
    top: "44px",
  },
  flowShow: {
    overflow: "visible",
  },
  controlCanvasWarper: {
    marginLeft: "-70px",
  },
  h33: {
    minHeight: "33px",
  },
  dropBox: {
    display: "none",
  },
  layer: {
    top: "92px",
  },
  mh180: {
    minHeight: "180px",
  },
  renderAllScene: {
    overflow: "scroll",
    height: "calc(105vh - 94px)",
    marginTop: "91px",
  },
  renderAllController: {
    height: "50px",
  },
  w50: {
    width: "50px",
  },
  colorPicker: {
    position: "fixed",
    top: "140px",
    right: "320px",
    width: "250px",
    height: "content-height",
    padding: 0,
  },
  colorPickerCircle: {
    height: "30px",
    width: "30px",
    border: "1px solid grey",
    borderRadius: "9999px",
  },
  btnPill: {
    padding: "7px 4px",
    width: "100%",
    border: "2px solid black",
    borderRadius: "9999px",
  },
};
